### ISSUE TITLE
引入 vue-loader 出现问题

### ISSUE THREAD

**Issue by chaucerling** [cantonjs/wxapp-boilerplate#43]
按 `vue-loader` 的教程和示例，在原配置上添加下面代码
``` js
// webpack.config.babel.js
import VueLoaderPlugin from 'vue-loader/lib/plugin';
module.exports = {
  mode: 'development',
  module: {
    rules: [
      {
        test: /\.vue$/,
        include: /src/,
        loader: 'vue-loader',
      },
      // 配置文件，使用 yaml 格式
      {
        resourceQuery: /blockType=config/,
        use: [
          relativeFileLoader('json'),
          'yaml-loader',
        ],
      },
    ]
  },
  plugins: [
    new VueLoaderPlugin()
  ]
}
```

``` vue
// pages/index/test.vue
<config>
navigationBarTitleText: 'tua-mp todos'
</config>

<template lang="axml">
  <view class="page">
    
  </view>
</template>

<script>
Page({
  data: {
    test: true
  }
})
</script>

<style lang="scss">
.page {
  color: #4d4d4d;
}
</style>
```

运行 `yarn start`，报错提示 `TypeError: Cannot read property 'replace' of undefined`，应该是没找到页面 js 入口文件。在 `pages/index/test.vue` 同一目录下添加 `test.js`，再运行 `yarn start`，还是报错。
```
ERROR in ./node_modules/vue-loader/lib/loaders/templateLoader.js?{}!./node_modules/file-loader/dist/cjs.js?{"name":"[path][name].wxml","context":"/Users/chaucerling/code/bestapp/rujia-xiaochengxu/src"}!./node_modules/wxml-loader/lib?{"root":"/Users/chaucerling/code/bestapp/rujia-xiaochengxu/src","enforceRelativePath":true}!./node_modules/vue-loader/lib?{}!./src/pages/index/test.vue?vue&type=template&id=5265ac9a&lang=axml&
(Emitted value instead of an instance of Error)
  Error compiling template:
  module.exports = __webpack_public_path__ + "pages/index/test.wxml";
  - Component template requires a root element, rather than just text.
```

**Comment by chaucerling** [comment]
[这篇文章](https://buptsteve.github.io/blog/2018/06/03/12.say-goodbye-to-mina-native/)提供了解决wxml 报错的方法，需要重写 `compiler` 的默认属性

``` js
{
  test: /\.vue$/,
  include: /src/,
  loader: 'vue-loader',
  options: {
    compiler: {
      // mock vue-template-compiler
      compile: () => ({
        staticRenderFns: [],
      }),
      parseComponent: require('vue-template-compiler')
        .parseComponent,
    },
  },
}
```

**Comment by chaucerling** [comment]
整理代码后发现，移除 `pages/index/test.js` 就报错了
```
TypeError: Cannot read property 'replace' of undefined
    at /Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/NormalModuleFactory.js:106:27
    at /Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/NormalModuleFactory.js:59:4
    at applyPluginsAsyncWaterfall (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/NormalModuleFactory.js:234:4)
    at /Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/tapable/lib/Tapable.js:268:11
    at IgnorePlugin.checkIgnore (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/IgnorePlugin.js:56:10)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/tapable/lib/Tapable.js:272:13)
    at NormalModuleFactory.create (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/NormalModuleFactory.js:218:8)
    at semaphore.acquire (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/Compilation.js:403:18)
    at Semaphore.acquire (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/util/Semaphore.js:16:4)
    at Compilation._addModuleChain (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/Compilation.js:402:18)
    at Compilation.addEntry (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/Compilation.js:490:8)
    at Compiler.compiler.plugin (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/wxapp-webpack-plugin/lib/index.js:486:16)
    at Compiler.applyPluginsParallel (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/tapable/lib/Tapable.js:293:14)
    at applyPluginsAsync.err (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/Compiler.js:503:9)
    at Compiler.applyPluginsAsyncSeries (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/tapable/lib/Tapable.js:195:46)
    at Compiler.compile (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/Compiler.js:496:8)
    at compiler.applyPluginsAsync.err (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/Compiler.js:82:18)
    at next (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/tapable/lib/Tapable.js:202:11)
    at Compiler.compiler.plugin (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/webpack/lib/CachePlugin.js:48:5)
    at next (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/tapable/lib/Tapable.js:204:14)
    at Compiler.<anonymous> (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/wxapp-webpack-plugin/lib/index.js:93:6)
    at Generator.next (<anonymous>)
    at step (/Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/wxapp-webpack-plugin/lib/index.js:42:191)
    at /Users/chaucerling/code/bestapp/rujia-xiaochengxu/node_modules/wxapp-webpack-plugin/lib/index.js:42:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
error Command failed with exit code 1.
```

**Comment by chaucerling** [comment]
查看 `wxapp-webpack-plugin` 源码，发现 `options` 提供了 `extensions` 参数作为入口文件的后缀名
在 webpack 配置里加上就编译成功了
